# Generated by Django 5.2.8 on 2025-11-22 17:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя узла')),
                ('elevation', models.FloatField(default=0, verbose_name='Отметка (высота)')),
                ('node_type', models.CharField(default='Junction', max_length=50, verbose_name='Тип узла')),
                ('base_demand', models.FloatField(default=0, verbose_name='Базовый расход')),
                ('fixed_head', models.FloatField(blank=True, null=True, verbose_name='Заданный напор')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Геометрия (Точка)')),
                ('calculated_pressure', models.FloatField(blank=True, null=True, verbose_name='Расчетное давление')),
            ],
            options={
                'verbose_name': 'Узел',
                'verbose_name_plural': 'Узлы',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя участка')),
                ('length', models.FloatField(verbose_name='Длина')),
                ('diameter', models.FloatField(verbose_name='Диаметр')),
                ('roughness_coefficient', models.FloatField(verbose_name='Коэффициент шероховатости')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Материал')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Геометрия (Линия)')),
                ('calculated_flow_rate', models.FloatField(blank=True, null=True, verbose_name='Расчетный расход')),
                ('calculated_velocity', models.FloatField(blank=True, null=True, verbose_name='Расчетная скорость')),
                ('calculated_head_loss', models.FloatField(blank=True, null=True, verbose_name='Расчетные потери напора')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_pipes', to='network_api.node', verbose_name='Начальный узел')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_pipes', to='network_api.node', verbose_name='Конечный узел')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipes', to='network_api.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Участок (Труба)',
                'verbose_name_plural': 'Участки (Трубы)',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='network_api.project', verbose_name='Проект'),
        ),
    ]
