"""
Django settings for hydraulic_calculator project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os

# Добавьте эти строки ПЕРЕД DATABASES:
# Правильные пути
os.environ['GDAL_DATA'] = r'C:/Users/malbo/AppData/Local/Programs/OSGeo4W/apps/gdal/share/gdal'
os.environ['PROJ_LIB'] = r'C:/Users/malbo/AppData/Local/Programs/OSGeo4W/share/proj'

GDAL_LIBRARY_PATH = r'C:/Users/malbo/AppData/Local/Programs/OSGeo4W/bin/gdal312.dll'
GEOS_LIBRARY_PATH = r'C:/Users/malbo/AppData/Local/Programs/OSGeo4W/bin/geos_c.dll'
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+fb2g1w19rceey8o^amixj)@j+*xdo&%jwgb&j-^3#a$%sj!&('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',

    # Сторонние приложения
    'rest_framework',
    'rest_framework_gis',
    'corsheaders',

    # Наши приложения
    'network_api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hydraulic_calculator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hydraulic_calculator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis', # Очень важно! Используем движок PostGIS
        'NAME': 'hydraulic_db',                             # Имя твоей БД
        'USER': 'hydraulic_user',                           # Имя пользователя
        'PASSWORD': 'user031104',        # Пароль
        'HOST': 'localhost',                                # Обычно localhost
        'PORT': '5432',                                     # Стандартный порт PostgreSQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# === НАСТРОЙКИ ДЛЯ РАБОТЫ С REACT ===

# 1. Разрешаем запросы с порта фронтенда (CORS)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# 2. Разрешаем передачу кук/креденшелов
CORS_ALLOW_CREDENTIALS = True

# 3. ВАЖНО! Доверяем этому источнику для CSRF (чтобы работали POST запросы)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# 4. Настройки доступа (DRF)
# Пока разрешаем доступ ВСЕМ (AllowAny), чтобы не мучиться с логином
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny', 
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}